### ISSUE TITLE
Feature Request - Public Key Authentication

### ISSUE THREAD

**Issue by roerohan** [GDGVIT/Compute-Monitoring-Bot#2]
# Feature Request - Public Key Authentication

A lot of people generally use public key auth instead of password auth for `ssh`-ing into their servers. It would be a cool feature if you accept a private key and use that instead of a password to login to the server.

@abhishekkushwaha4u nice bot by the way :smile:

**Comment by abhishekkushwaha4u** [comment]
A nice idea, would love to work on it. Thanks!
